openapi: 3.0.0
info:
  title: Spaceships API
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local server

paths:
  /api/v1/auth/login:
    post:
      summary: Authenticate user and generate JWT token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginUserRequest'
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '401':
          description: Unauthorized
  /api/v1/auth/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterUserRequest'
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        '400':
          description: Bad request

  /api/v1/spaceships:
    get:
      summary: List all spaceships
      responses:
        '200':
          description: A list of spaceships
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Spaceship'
    post:
      summary: Create a new spaceship
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SpaceshipRequest'
      responses:
        '201':
          description: Spaceship created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        '400':
          description: Bad request
  /api/v1/spaceships/{id}:
    get:
      summary: Get a spaceship by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A spaceship
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Spaceship'
        '404':
          description: Not found
    put:
      summary: Update a spaceship by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SpaceshipRequest'
      responses:
        '200':
          description: Spaceship updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        '404':
          description: Not found
    delete:
      summary: Delete a spaceship by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: No content
        '404':
          description: Not found

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
        role:
          $ref: '#/components/schemas/Role'
    Spaceship:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        type:
          type: string
    LoginUserRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
    RegisterUserRequest:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
    LoginResponse:
      type: object
      properties:
        token:
          type: string
        expiresIn:
          type: integer
    SpaceshipRequest:
      type: object
      properties:
        name:
          type: string
        series:
          type: string
        type:
          type: string
    ApiResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
    Role:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string

securitySchemes:
  bearerAuth:
    type: http
    scheme: bearer
    bearerFormat: JWT
